services:
    CoreShop\Bundle\MarketWarehouseBundle\Package\CompositeOrderPackageProcessor: ~

    CoreShop\Bundle\MarketWarehouseBundle\Package\Calculator\DeliveryTimeCalculatorInterface: '@CoreShop\Bundle\MarketWarehouseBundle\Package\Calculator\DeliveryTimeCalculator'
    CoreShop\Bundle\MarketWarehouseBundle\Package\Calculator\DeliveryTimeCalculator:
        arguments:
            - '@CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseDeliveryTimeProcessorInterface'
            - '@CoreShop\Component\Core\Provider\AddressProviderInterface'

    CoreShop\Bundle\MarketWarehouseBundle\Package\PackagerInterface: '@CoreShop\Bundle\MarketWarehouseBundle\Package\Packager'
    CoreShop\Bundle\MarketWarehouseBundle\Package\Packager:
        arguments:
            - '@coreshop_market_warehouse.repository.supplier_sale_rule'
            - '@coreshop_market_warehouse.repository.product_warehouse_stock'
            - '@coreshop_market_warehouse.factory.order_package'
            - '@coreshop_market_warehouse.factory.order_package_item'
            - '@CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseValidationProcessorInterface'
            - '@CoreShop\Component\Order\Cart\CartContextResolverInterface'
            - '@CoreShop\Component\Core\Provider\AddressProviderInterface'

    CoreShop\Bundle\MarketWarehouseBundle\Order\Processor\OrderPackageProcessor:
        arguments:
            - '@coreshop_market_warehouse.repository.order_package'
            - '@CoreShop\Bundle\MarketWarehouseBundle\Package\PackagerInterface'
            - '@CoreShop\Bundle\MarketWarehouseBundle\Package\CompositeOrderPackageProcessor'
            - '@coreshop.factory.adjustment'
        tags:
          - { name: coreshop.cart_processor }

    CoreShop\Bundle\MarketWarehouseBundle\Package\Processor\OrderPackagePriceProcessor:
        tags:
            - { name: coreshop_market_warehouse.order.package_processor, priority: 100 }

    CoreShop\Bundle\MarketWarehouseBundle\Package\Processor\OrderPackageWeightProcessor:
        tags:
            - { name: coreshop_market_warehouse.order.package_processor, priority: 200 }

    CoreShop\Bundle\MarketWarehouseBundle\Package\Processor\ShippingProcessor:
        arguments:
            - '@CoreShop\Component\Order\Cart\CartContextResolverInterface'
            - '@coreshop.carrier.price_calculator.taxed'
            - '@coreshop.shipping.carrier.validator'
            - '@coreshop.carrier.resolver'
            - '@coreshop.provider.store_based_default_address_provider'
        tags:
            - { name: coreshop_market_warehouse.order.package_processor, priority: 300 }

    CoreShop\Bundle\MarketWarehouseBundle\Package\Processor\DeliveryTimeProcessor:
        arguments:
            - '@CoreShop\Bundle\MarketWarehouseBundle\Package\Calculator\DeliveryTimeCalculatorInterface'
            - '@CoreShop\Component\Order\Cart\CartContextResolverInterface'
        tags:
            - { name: coreshop_market_warehouse.order.package_processor, priority: 400 }
