services:
    CoreShop\Bundle\MarketWarehouseBundle\Package\CompositeOrderPackageProcessor: ~

    CoreShop\Bundle\MarketWarehouseBundle\Package\PackagerInterface: '@CoreShop\Bundle\MarketWarehouseBundle\Package\Packager'
    CoreShop\Bundle\MarketWarehouseBundle\Package\Packager:
        arguments:
            - '@coreshop.repository.supplier_sale_rule'
            - '@coreshop.repository.product_warehouse_stock'
            - '@coreshop.factory.order_package'
            - '@coreshop.factory.order_package_item'

    CoreShop\Bundle\MarketWarehouseBundle\Order\Processor\OrderPackageProcessor:
        arguments:
            - '@coreshop.repository.order_package'
            - '@CoreShop\Bundle\MarketWarehouseBundle\Package\PackagerInterface'
            - '@CoreShop\Bundle\MarketWarehouseBundle\Package\CompositeOrderPackageProcessor'
            - '@coreshop.factory.adjustment'
        tags:
          - { name: coreshop.cart_processor }

    CoreShop\Bundle\MarketWarehouseBundle\Package\Processor\OrderPackagePriceProcessor:
        tags:
            - { name: coreshop.order.package_processor, priority: 100 }

    CoreShop\Bundle\MarketWarehouseBundle\Package\Processor\OrderPackageWeightProcessor:
        tags:
            - { name: coreshop.order.package_processor, priority: 200 }

    CoreShop\Bundle\MarketWarehouseBundle\Package\Processor\ShippingProcessor:
        arguments:
            - '@coreshop.carrier.price_calculator.taxed'
            - '@coreshop.shipping.carrier.validator'
            - '@coreshop.carrier.resolver'
            - '@coreshop.provider.store_based_default_address_provider'
        tags:
            - { name: coreshop.order.package_processor, priority: 300 }

    CoreShop\Bundle\MarketWarehouseBundle\Package\Processor\DeliveryTimeProcessor:
        tags:
            - { name: coreshop.order.package_processor, priority: 400 }
