services:
    _defaults:
        public: true

    #CoreShop\Bundle\MarketWarehouseBundle\SubOrder\CompositeSubOrderProcessor: ~

    CoreShop\Bundle\MarketWarehouseBundle\SubOrder\SubOrderCreatorInterface: '@CoreShop\Bundle\MarketWarehouseBundle\SubOrder\SubOrderCreator'
    CoreShop\Bundle\MarketWarehouseBundle\SubOrder\SubOrderCreator:
        arguments:
            - '@coreshop_market_warehouse.factory.sub_order'
            - '@coreshop_market_warehouse.factory.sub_order_item'
            - '@CoreShop\Component\Order\Cart\CartContextResolverInterface'
            - '@CoreShop\Component\Resource\Service\FolderCreationServiceInterface'