services:
    coreshop_market_warehouse.registry.supplier_shipping.actions:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Component\Shipping\Rule\Action\CarrierPriceActionProcessorInterface
            - warehouse-delivery-time-action
        tags:
            - { name: coreshop.registry, type_hint: warehouseShippingActions }

    coreshop_market_warehouse.form_registry.supplier_shipping.actions:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    coreshop_market_warehouse.registry.supplier_shipping.conditions:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Component\Rule\Condition\ConditionCheckerInterface
            - warehouse-delivery-time-condition
        tags:
            - { name: coreshop.registry, type_hint: warehouseShippingConditions }

    coreshop_market_warehouse.form_registry.supplier_shipping.conditions:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    coreshop_market_warehouse.supplier_shipping.conditions.processor:
        class: CoreShop\Component\Rule\Condition\RuleConditionsValidationProcessor
        shared: false
        arguments:
            - '@coreshop_market_warehouse.registry.supplier_shipping.conditions'
            - 'Shipping Rules'

    coreshop_market_warehouse.supplier_shipping.processor:
        class: CoreShop\Component\Rule\Condition\RuleValidationProcessor
        shared: false
        arguments:
            - '@coreshop_market_warehouse.supplier_shipping.conditions.processor'

    CoreShop\Bundle\MarketWarehouseBundle\Package\Shipping\SupplierCarrierResolver:
        decorates: 'coreshop.carrier.resolver'
        arguments:
            - '@CoreShop\Bundle\MarketWarehouseBundle\Package\Shipping\SupplierCarrierResolver.inner'

    coreshop_market_warehouse.supplier_shipping.condition.amount:
        class: CoreShop\Component\Shipping\Rule\Condition\AmountConditionChecker
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.condition, type: amount, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\AmountConfigurationType }

    coreshop_market_warehouse.supplier_shipping.condition.postcodes:
        class: CoreShop\Component\Shipping\Rule\Condition\PostcodeConditionChecker
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.condition, type: postcodes, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\PostcodeConfigurationType }

    coreshop_market_warehouse.supplier_shipping.condition.weight:
        class: CoreShop\Component\Shipping\Rule\Condition\WeightConditionChecker
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.condition, type: weight, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\WeightConfigurationType }

    coreshop_market_warehouse.supplier_shipping.condition.dimension:
        class: CoreShop\Component\Shipping\Rule\Condition\DimensionConditionChecker
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.condition, type: dimension, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\DimensionConfigurationType }

    coreshop_market_warehouse.supplier_shipping.condition.nested:
        class: CoreShop\Component\Rule\Condition\NestedConditionChecker
        arguments:
            - '@coreshop_market_warehouse.supplier_shipping.conditions.processor'
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.condition, type: nested, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Condition\NestedConfigurationType }

    coreshop_market_warehouse.supplier_shipping.action.addition_percent:
        class: CoreShop\Component\Shipping\Rule\Action\AdditionPercentActionProcessor
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.action, type: additionPercent, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Action\AdditionPercentActionConfigurationType }

    coreshop_market_warehouse.supplier_shipping.action.discount_percent:
        class: CoreShop\Component\Shipping\Rule\Action\DiscountPercentActionProcessor
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.action, type: discountPercent, form-type: CoreShop\Bundle\ShippingBundle\Form\Type\Rule\Action\DiscountPercentActionConfigurationType }

    coreshop_market_warehouse.supplier_shipping.action.addition_amount:
        class: CoreShop\Component\Core\Shipping\Rule\Action\AdditionAmountActionProcessor
        arguments:
            - '@coreshop.repository.currency'
            - '@coreshop.currency_converter'
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.action, type: additionAmount, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Shipping\Rule\Action\AdditionAmountActionConfigurationType }

    coreshop_market_warehouse.supplier_shipping.action.discount_amount:
        class: CoreShop\Component\Core\Shipping\Rule\Action\DiscountAmountActionProcessor
        arguments:
            - '@coreshop.repository.currency'
            - '@coreshop.currency_converter'
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.action, type: discountAmount, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Shipping\Rule\Action\DiscountAmountActionConfigurationType }

    coreshop_market_warehouse.supplier_shipping.action.price:
        class: CoreShop\Component\Core\Shipping\Rule\Action\PriceActionProcessor
        arguments:
            - '@coreshop.repository.currency'
            - '@coreshop.currency_converter'
        tags:
            - { name: coreshop_market_warehouse.supplier_shipping.action, type: price, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Shipping\Rule\Action\PriceActionConfigurationType }
