services:
    CoreShop\Bundle\MarketWarehouseBundle\Twig\Extension\OrderPackageExtension:
        arguments:
            - '@coreshop_market_warehouse.repository.order_package'
        tags:
            - { name: twig.extension }
