services:
    coreshop_market_warehouse.registry.warehouse_delivery_time.actions:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\Action\WarehouseDeliveryTimeActionProcessorInterface
            - warehouse-delivery-time-action
        tags:
            - { name: coreshop.registry, type_hint: warehouseDeliveryTimeActions }

    coreshop_market_warehouse.form_registry.warehouse_delivery_time.actions:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    coreshop_market_warehouse.registry.warehouse_delivery_time.conditions:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\Condition\WarehouseDeliveryTimeConditionCheckerInterface
            - warehouse-delivery-time-condition
        tags:
            - { name: coreshop.registry, type_hint: warehouseDeliveryTimeConditions }

    coreshop_market_warehouse.form_registry.warehouse_delivery_time.conditions:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    coreshop_market_warehouse.warehouse_delivery_time.conditions.processor:
        class: CoreShop\Component\Rule\Condition\RuleConditionsValidationProcessor
        shared: false
        arguments:
            - '@coreshop_market_warehouse.registry.warehouse_delivery_time.conditions'
            - 'Shipping Rules'

    coreshop_market_warehouse.warehouse_delivery_time.processor:
        class: CoreShop\Component\Rule\Condition\RuleValidationProcessor
        shared: false
        arguments:
            - '@coreshop_market_warehouse.warehouse_delivery_time.conditions.processor'

    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseDeliveryTimeProcessorInterface: '@CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseDeliveryTimeProcessor'
    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseDeliveryTimeProcessor:
        arguments:
            - '@coreshop_market_warehouse.registry.warehouse_delivery_time.actions'
            - '@CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseRuleCheckerInterface'

    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseValidationProcessorInterface: '@CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseValidationProcessor'
    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseValidationProcessor:
        arguments:
            - '@coreshop_market_warehouse.registry.warehouse_delivery_time.actions'
            - '@CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseRuleCheckerInterface'

    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseRuleCheckerInterface: '@CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseRuleChecker'
    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\WarehouseRuleChecker:
        arguments:
            - '@coreshop_market_warehouse.warehouse_delivery_time.processor'

    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\Condition\PostcodeConditionChecker:
        tags:
            - { name: coreshop_market_warehouse.warehouse_delivery_time.condition, type: postcodes, form-type: CoreShop\Bundle\MarketWarehouseBundle\Form\Type\Rule\DeliveryTime\Condition\PostcodeConfigurationType }

    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\Action\DaysActionProcessor:
        tags:
            - { name: coreshop_market_warehouse.warehouse_delivery_time.action, type: days, form-type: CoreShop\Bundle\MarketWarehouseBundle\Form\Type\Rule\DeliveryTime\Action\DaysConfigurationType }

    CoreShop\Bundle\MarketWarehouseBundle\Rule\DeliveryTime\Action\InvalidActionProcessor:
        tags:
            - { name: coreshop_market_warehouse.warehouse_delivery_time.action, type: invalid }
