services:
    coreshop.registry.market_warehouse.warehouse_delivery_time.actions:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Bundle\MarketWarehouseBundle\Rule\Action\WarehouseDeliveryTimeActionProcessorInterface
            - warehouse-delivery-time-action
        tags:
            - { name: coreshop.registry, type_hint: warehouseDeliveryTimeActions }

    coreshop.form_registry.market_warehouse.warehouse_delivery_time.actions:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    coreshop.registry.market_warehouse.warehouse_delivery_time.conditions:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Bundle\MarketWarehouseBundle\Rule\Condition\WarehouseDeliveryTimeConditionCheckerInterface
            - warehouse-delivery-time-condition
        tags:
            - { name: coreshop.registry, type_hint: warehouseDeliveryTimeConditions }

    coreshop.form_registry.market_warehouse.warehouse_delivery_time.conditions:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    coreshop.warehouse_market.warehouse_delivery_time.conditions.processor:
        class: CoreShop\Component\Rule\Condition\RuleConditionsValidationProcessor
        shared: false
        arguments:
            - '@coreshop.registry.market_warehouse.warehouse_delivery_time.conditions'
            - 'Shipping Rules'

    coreshop.warehouse_market.warehouse_delivery_time.processor:
        class: CoreShop\Component\Rule\Condition\RuleValidationProcessor
        shared: false
        arguments:
            - '@coreshop.warehouse_market.warehouse_delivery_time.conditions.processor'


    CoreShop\Bundle\MarketWarehouseBundle\Rule\Condition\PostcodeConditionChecker:
        tags:
            - { name: coreshop.market_warehouse.warehouse_delivery_time.condition, type: postcodes, form-type: CoreShop\Bundle\MarketWarehouseBundle\Form\Type\Rule\Condition\PostcodeConfigurationType }

    CoreShop\Bundle\MarketWarehouseBundle\Rule\Action\DaysActionProcessor:
        tags:
            - { name: coreshop.market_warehouse.warehouse_delivery_time.action, type: days, form-type: CoreShop\Bundle\MarketWarehouseBundle\Form\Type\Rule\Action\DaysConfigurationType }
