parameters:
    coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.validation_groups: [coreshop]
    coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.rule_action.validation_groups: [coreshop]
    coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.rule_condition.validation_groups: [coreshop]
    coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.condition.postcode.validation_groups: [coreshop]
    coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.action.days.validation_groups: [coreshop]

services:
    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\WarehouseDeliveryTimeRuleType:
        arguments:
            - '%coreshop_market_warehouse.model.warehouse_delivery_time_rule.class%'
            - '%coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.validation_groups%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\WarehouseDeliveryTimeRuleActionType:
        arguments:
            - '%coreshop.model.rule_action.class%'
            - '%coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.rule_action.validation_groups%'
            - '@coreshop_market_warehouse.form_registry.warehouse_delivery_time.actions'
        tags:
            - { name: form.type }

    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\WarehouseDeliveryTimeRuleActionCollectionType:
        arguments:
            - '@coreshop_market_warehouse.registry.warehouse_delivery_time.actions'
        tags:
            - { name: form.type }

    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\WarehouseDeliveryTimeRuleActionChoiceType:
        arguments:
            - '%coreshop_market_warehouse.warehouse_delivery_time.actions%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\WarehouseDeliveryTimeRuleConditionType:
        arguments:
            - '%coreshop.model.rule_condition.class%'
            - '%coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.rule_condition.validation_groups%'
            - '@coreshop_market_warehouse.form_registry.warehouse_delivery_time.conditions'
        tags:
            - { name: form.type }

    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\WarehouseDeliveryTimeRuleConditionCollectionType:
        arguments:
            - '@coreshop_market_warehouse.registry.warehouse_delivery_time.conditions'
        tags:
            - { name: form.type }

    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\WarehouseDeliveryTimeRuleConditionChoiceType:
        arguments:
            - '%coreshop_market_warehouse.warehouse_delivery_time.conditions%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\Rule\DeliveryTime\Condition\PostcodeConfigurationType:
        arguments:
            - '%coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.condition.postcode.validation_groups%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\MarketWarehouseBundle\Form\Type\Rule\DeliveryTime\Action\DaysConfigurationType:
        arguments:
            - '%coreshop_market_warehouse.form.type.warehouse_delivery_time_rule.action.days.validation_groups%'
        tags:
            - { name: form.type }
