version: '3.4'

networks:
  cors_dev:
    external: true
  coreshop_mw:
    external: false

services:
    db:
      image: mysql:8
      container_name: coreshop-mw-database
      networks:
          - cors_dev
          - coreshop_mw
      working_dir: /application
      volumes:
          - coreshop-mw-database:/var/lib/mysql
      environment:
          - MYSQL_ROOT_PASSWORD=ROOT
          - MYSQL_DATABASE=pimcore
          - MYSQL_USER=pimcore
          - MYSQL_PASSWORD=pimcore

    nginx:
      image: nginx:stable-alpine
      container_name: coreshop-mw-nginx
      labels:
        - traefik.enable=true
        - traefik.http.routers.suzuki.rule=HostRegexp(`market-warehouse.localhost`)
        - traefik.http.routers.suzuki.entrypoints=cors_dev
        - traefik.http.routers.suzuki.tls=true
        - traefik.http.services.suzuki.loadbalancer.server.port=80
        - traefik.docker.network=cors_dev
      networks:
        - cors_dev
        - coreshop_mw
      volumes:
        - nfsmount:/var/www/html:ro
        - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - php
        - php-debug

    php:
      image: git.e-conomix.at:5050/cors/docker/php-alpine-fpm:8.0-LATEST
      container_name: php-coreshop-mw
      command: 'php-fpm'
      entrypoint: docker-php-entrypoint
      networks:
        - coreshop_mw
        - cors_dev
      depends_on:
        - db
      volumes:
        - nfsmount:/var/www/html:cached
        - ./.docker/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-additional.ini:ro
      environment:
        - COMPOSER_AUTH=${COMPOSER_AUTH}

    php-debug:
      image: git.e-conomix.at:5050/cors/docker/php-alpine-fpm-debug:8.0-LATEST
      container_name: php-coreshop-mw-debug
      command: 'php-fpm'
      entrypoint: xdebug-entrypoint
      depends_on:
        - db
      volumes:
        - nfsmount:/var/www/html:cached
        - ./.docker/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-additional.ini:ro
      networks:
        - coreshop_mw
        - cors_dev
      environment:
        - PHP_IDE_CONFIG=serverName=localhost
        - COMPOSER_AUTH=${COMPOSER_AUTH:-}

volumes:
    coreshop-mw-database:
    nfsmount:
      driver: local
      driver_opts:
        type: nfs
        o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
        device: ":${PWD}"