version: '3.4'

networks:
    cors_dev:
        external: true
services:
    db:
        image: mysql:8
        container_name: coreshop-market-warehouse-bundle-mariadb
        networks:
            - cors_dev
        working_dir: /application
        command: [ mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_general_ci ]
        volumes:
            - coreshop-market-warehouse-bundle-database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore

    php:
        image: pimcore/pimcore:PHP8.0-apache
        container_name: coreshop-market-warehouse-bundle-php
        networks:
          - cors_dev
        labels:
          - traefik.enable=true
          - traefik.http.routers.market_warehouse.rule=Host(`market-warehouse.localhost`)
          - traefik.http.routers.market_warehouse.entrypoints=cors_dev
          - traefik.http.routers.market_warehouse.tls=true
          - traefik.http.services.market_warehouse.loadbalancer.server.port=80
          - traefik.docker.network=cors_dev
        volumes:
            - .:/var/www/html:cached
        depends_on:
            - db

    php-debug:
        image: pimcore/pimcore:PHP8.0-apache-debug
        container_name: coreshop-market-warehouse-bundle-debug-php
        networks:
          - cors_dev
        labels:
          - traefik.enable=true
          - traefik.http.routers.market_warehouse_debug.rule=Host(`market-warehouse.localhost`)
          - traefik.http.routers.market_warehouse_debug.entrypoints=cors_dev_debug
          - traefik.http.routers.market_warehouse_debug.tls=true
          - traefik.http.services.market_warehouse_debug.loadbalancer.server.port=80
          - traefik.docker.network=cors_dev
        volumes:
            - .:/var/www/html:cached
        depends_on:
            - db
        environment:
            - PHP_DEBUG=1
            - PHP_IDE_CONFIG="serverName=localhost"

volumes:
    coreshop-market-warehouse-bundle-database:
