version: '3.8'

networks:
  cors_dev:
    external: true
  mw:
    external: false

services:
  redis:
    container_name: mw-redis
    image: redis:alpine
    command: redis-server --requirepass password
    networks:
      - mw

  db:
    image: mysql:8
    container_name: mw
    networks:
      - cors_dev
      - mw
    working_dir: /application
    volumes:
      - mw-database:/var/lib/mysql
      - ./:/application
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  nginx:
    image: nginx:stable-alpine
    container_name: mw-nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.mw.rule=HostRegexp(`market-warehouse.localhost`, `{subdomain:(.*)}.market-warehouse.localhost`)
      - traefik.http.routers.mw.entrypoints=cors_dev
      - traefik.http.routers.mw.tls=true
      - traefik.http.services.mw.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev
    networks:
      - cors_dev
      - mw
    volumes:
      - ./:/var/www/html:ro
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - php-debug

  php:
    image: git.e-conomix.at:5050/cors/docker/php-alpine-3.17-fpm:8.1-LATEST
    container_name: php-mw
    command: 'php-fpm'
    entrypoint: docker-php-entrypoint
    networks:
      - mw
      - cors_dev
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-additional.ini:ro
    environment:
      - COMPOSER_AUTH=${COMPOSER_AUTH}

  php-debug:
    image: git.e-conomix.at:5050/cors/docker/php-alpine-3.17-fpm-debug:8.1-LATEST
    container_name: php-debug-mw
    command: 'php-fpm'
    entrypoint: xdebug-entrypoint
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-additional.ini:ro
    networks:
      - mw
      - cors_dev
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
      - COMPOSER_AUTH=${COMPOSER_AUTH:-}

volumes:
  mw-database: