doctrine:
    dbal:
        connections:
            default:
                host: coreshop-market-warehouse-bundle-mariadb
                port: 3306
                user: pimcore
                password: pimcore
                dbname: pimcore
                server_version: '10.5'

