doctrine:
    dbal:
        connections:
            default:
                host: coreshop-market-warehouse-bundle-mariadb
                port: 3306
                user: root
                password: ROOT
                dbname: pimcore
                server_version: '10.5'

