doctrine:
    dbal:
        connections:
            default:
                host: coreshop-mw-database
                port: 3306
                user: root
                password: ROOT
                dbname: pimcore
                server_version: '8'

