imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: migrations.yaml }
    - { resource: system.yml }
    - { resource: 'local/' }
    - { resource: '@PimcoreCoreBundle/Resources/config/pimcore/config.yml' }
    - { resource: '@CoreShopCoreBundle/Resources/config/config.yml' }
    - { resource: '@CoreShopMarketWarehouseBundle/Resources/config/pimcore/config.yml' }

framework:
    profiler:
        enabled: false

core_shop_core:
    checkout_manager_factory: packaging
    checkout:
        packaging:
            steps:
                customer:
                  step: CoreShop\Bundle\CoreBundle\Checkout\Step\CustomerCheckoutStep
                  priority: 10
                address:
                  step: CoreShop\Bundle\CoreBundle\Checkout\Step\AddressCheckoutStep
                  priority: 20
                shipping:
                  step: CoreShop\Bundle\MarketWarehouseBundle\Checkout\OrderPackageShippingStep
                  priority: 30
                payment:
                  step: CoreShop\Bundle\CoreBundle\Checkout\Step\PaymentCheckoutStep
                  priority: 40
                summary:
                  step: CoreShop\Bundle\CoreBundle\Checkout\Step\SummaryCheckoutStep
                  priority: 50
