imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: migrations.yaml }
    - { resource: system.yml }
    - { resource: 'local/' }

framework:
    profiler:
        enabled: false
