framework:
    workflows:
        coreshop_sub_order:
            type: 'state_machine'
            marking_store:
                service: coreshop.state_machine.marking_store.sub_order_pimcore_marking_store
            supports: CoreShop\Bundle\MarketWarehouseBundle\Model\SubOrder

core_shop_workflow:
    state_machine:
        coreshop_sub_order:
            places:
                - initialized
                - new
                - cancelled
                - complete
            transitions:
                create:
                    from: initialized
                    to: new
                cancel:
                    from: new
                    to:   cancelled
                complete:
                    from: new
                    to:   complete
            place_colors:
                initialized: '#d6e1dd'
                new: '#61c2cb'
                cancelled: '#f2583e'
                complete: '#5b981a'
            transition_colors:
                create: '#feb624'
                cancel: '#f2583e'
                complete: '#5b981a'
            # TODO: callbacks