core_shop_workflow:
    state_machine:
        coreshop_order_sales_type:
            callbacks:
                after:
                    create_suborder:
                        on: ['order']
                        do: ['@CoreShop\Bundle\MarketWarehouseBundle\SubOrder\SubOrderCreatorInterface', 'createSubOrder']
                        args: ['object']
        coreshop_order:
            callbacks:
                after:
                    suborder_cascade:
                        on: ['confirm', 'cancel']
                        do: ['@CoreShop\Bundle\MarketWarehouseBundle\StateMachine\CascadeSuborderTransition', 'apply']
                        args: ['object', 'event']
                    order_cascade_cancel:
                        on: ['cancel']
                        do: ['@CoreShop\Bundle\MarketWarehouseBundle\StateMachine\MainOrderStateResolver', 'resolveState']
                        args: ['object']
                    suborder_cascade_immutability:
                        on: ['confirm']
                        do: ['@CoreShop\Bundle\MarketWarehouseBundle\StateMachine\CascadeSuborderCallback', 'apply']
                        args: ['object', '"CoreShop\\Component\\Order\\Modifier\\ImmutabilityModifierInterface"', '"makeImmutable"', '"object"']
                    packages_immutability:
                        on: ['confirm']
                        do: ['@CoreShop\Bundle\MarketWarehouseBundle\StateMachine\PackagesImmutabilityModifier', 'makeImmutable']
                        args: ['object']
        coreshop_order_payment:
            callbacks:
                after:
                    suborder_cascade:
                        on: ['request_payment', 'authorize', 'cancel', 'pay']
                        do: ['@CoreShop\Bundle\MarketWarehouseBundle\StateMachine\CascadeSuborderTransition', 'apply']
                        args: ['object', 'event']
