CoreShop\Bundle\MarketWarehouseBundle\Model\SubOrder:
    exclusion_policy: ALL
    xml_root_name: order
    virtual_properties:
        subtotalNet:
            serialized_name: subtotalNet
            exp: object.getSubtotal(false)
            type: integer
            groups: [List, Detailed]
        subtotalGross:
            serialized_name: subtotalGross
            exp: object.getSubtotal(true)
            type: integer
            groups: [List, Detailed]
        #convertedSubtotalNet:
        #    serialized_name: convertedSubtotalNet
        #    exp: object.getConvertedSubtotal(false)
        #    type: integer
        #    groups: [List, Detailed]
        #convertedSubtotalGross:
        #    serialized_name: convertedSubtotalGross
        #    exp: object.getConvertedSubtotal(true)
        #    type: integer
        #    groups: [List, Detailed]
        shippingNet:
            serialized_name: shippingNet
            exp: object.getShipping(false)
            type: integer
            groups: [Detailed]
        shippingGross:
            serialized_name: shippingGross
            exp: object.getShipping(true)
            type: integer
            groups: [List, Detailed]
        #convertedShippingNet:
        #    serialized_name: convertedSshippingNet
        #    exp: object.getConvertedShipping(false)
        #    type: integer
        #    groups: [List, Detailed]
        #convertedShippingGross:
        #    serialized_name: convertedShippingGross
        #    exp: object.getConvertedShipping(true)
        #    type: integer
        #    groups: [List, Detailed]
        order:
            serialized_name: order
            exp: object.getOrder()
            groups: [ Detailed ]
        items:
            serialized_name: items
            exp: object.getItems()
            groups: [List, Detailed]
        packages:
            serialized_name: packages
            exp: object.getPackages()
            groups: [List, Detailed]