imports:
    - { resource: admin.yml }

pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopMarketWarehouseWarehouseDeliveryTimeRule: CoreShop\Bundle\MarketWarehouseBundle\CoreExtension\WarehouseDeliveryTimeRule
                    coreShopMarketWarehouseSupplierShippingRule: CoreShop\Bundle\MarketWarehouseBundle\CoreExtension\SupplierShippingRule

jms_serializer:
    metadata:
        directories:
            coreshop-market-warehouse:
                namespace_prefix: "CoreShop\\Bundle\\MarketWarehouseBundle"
                path: "@CoreShopMarketWarehouseBundle/Resources/config/serializer"
