coreshop_market_warehouse_admin_sub_order_update_state:
    path: /%coreshop.admin.route.base%/order/update-suborder-state
    defaults: { _controller: CoreShop\Bundle\MarketWarehouseBundle\Controller\SubOrderController::updateOrderStateAction}
    options:
        expose: true